from __future__ import annotations

import difflib
import subprocess
import sys

from mypy_primer.model import Project

# projects to re-enable:
# - https://github.com/edgedb/edgedb
# - https://github.com/twisted/twisted (needs mypy-zope plugin)

# repos with plugins
# - https://github.com/dry-python/returns
# - https://github.com/strawberry-graphql/strawberry
# - https://github.com/r-spacex/submanager
# - https://github.com/NeilGirdhar/efax
# - https://github.com/google/duet
# - https://github.com/typeddjango/django-stubs

# repos with issues
# - https://github.com/RobertCraigie/prisma-client-py
#   has a codegen build step that provides a lot of the regression check value


def update_projects(projects: list[Project], check: bool = False) -> None:
    # modifies `get_projects` in place.
    result = []
    with open(__file__) as f:
        keep = True
        for line in f:
            if line.endswith("\n"):
                line = line[:-1]
            if line == "    projects = [":
                result.append(f"    projects = {projects!r}")
                keep = False
            if keep:
                result.append(line)
            if line == "    ]":
                keep = True

    if check:
        code_proc = subprocess.run(
            ["black", "-"], input="\n".join(result), capture_output=True, text=True
        )
        code_proc.check_returncode()
        code = code_proc.stdout

        with open(__file__) as f:
            in_file = f.read()
            if in_file != code:
                diff = difflib.context_diff(
                    in_file.splitlines(keepends=True),
                    code.splitlines(keepends=True),
                    fromfile=__file__,
                    tofile=__file__,
                )
                print("".join(diff))
                sys.exit(1)
    else:
        with open(__file__, "w") as f:
            f.write("\n".join(result))


def get_projects() -> list[Project]:
    projects = [
        Project(
            location="https://github.com/python/mypy",
            mypy_cmd="{mypy} --config-file mypy_self_check.ini -p mypy -p mypyc",
            pyright_cmd="{pyright} {paths}",
            paths=["mypy", "mypyc"],
            deps=["pytest", "types-psutil", "types-setuptools", "filelock", "tomli"],
            expected_success=("mypy",),
            cost={"mypy": 55, "pyright": 50},
        ),
        Project(
            location="https://github.com/hauntsaninja/mypy_primer",
            mypy_cmd="{mypy} -p mypy_primer --strict",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/psf/black",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["aiohttp", "click", "pathspec", "tomli", "platformdirs", "packaging"],
            expected_success=("mypy",),
            cost={"mypy": 20},
        ),
        Project(
            location="https://github.com/hauntsaninja/pyp",
            mypy_cmd="{mypy} --strict -m pyp",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            expected_success=("mypy",),
            cost={"mypy": 4},
        ),
        Project(
            location="https://github.com/pytest-dev/pytest",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "testing"],
            deps=["attrs", "pluggy", "py", "types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 32},
        ),
        Project(
            location="https://github.com/pandas-dev/pandas",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pandas"],
            deps=[
                "numpy",
                "types-python-dateutil",
                "types-pytz",
                "types-PyMySQL",
                "types-setuptools",
                "pytest",
            ],
            expected_success=("mypy",),
            cost={"mypy": 197},
        ),
        Project(
            location="https://github.com/pycqa/pylint",
            mypy_cmd="{mypy} {paths} --ignore-missing-imports",
            pyright_cmd="{pyright} {paths}",
            paths=["pylint/checkers"],
            deps=["types-toml"],
            expected_success=("mypy",),
            cost={"mypy": 18},
        ),
        Project(
            location="https://github.com/aio-libs/aiohttp",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["aiohttp"],
            install_cmd="AIOHTTP_NO_EXTENSIONS=1 {install} -e .",
            deps=["pytest"],
            expected_success=("mypy",),
            cost={"mypy": 20},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/python-attrs/attrs",
            mypy_cmd="{mypy} src/attr/__init__.pyi src/attr/_version_info.pyi src/attr/converters.pyi src/attr/exceptions.pyi src/attr/filters.pyi src/attr/setters.pyi src/attr/validators.pyi tests/typing_example.py",
            pyright_cmd="{pyright}",
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/sphinx-doc/sphinx",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["sphinx"],
            deps=["babel", "docutils-stubs", "types-requests", "packaging", "jinja2"],
            cost={"mypy": 35},
        ),
        Project(
            location="https://github.com/scikit-learn/scikit-learn",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["sklearn"],
            deps=["joblib", "numpy", "scipy-stubs", "threadpoolctl"],
            expected_success=("mypy",),
            cost={"mypy": 108, "pyright": 240},
        ),
        Project(
            location="https://github.com/pypa/bandersnatch",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["types-filelock", "types-freezegun", "types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/hauntsaninja/boostedblob",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["boostedblob"],
            deps=["aiohttp", "uvloop", "pycryptodome"],
            expected_success=("mypy",),
            cost={"mypy": 17},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/quora/asynq",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["asynq"],
            deps=["qcore", "pytest"],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/scrapy/scrapy",
            mypy_cmd="{mypy} scrapy tests",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["attrs", "types-pyOpenSSL", "types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 23},
        ),
        Project(
            location="https://github.com/pypa/twine",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["twine"],
            deps=["keyring", "types-requests", "rich", "packaging"],
            expected_success=("mypy",),
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/more-itertools/more-itertools",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["more_itertools"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/pydata/xarray",
            mypy_cmd="{mypy} --exclude conftest.py",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=[
                "numpy",
                "packaging",
                "pandas-stubs",
                "types-PyYAML",
                "types-Pygments",
                "types-colorama",
                "types-decorator",
                "types-defusedxml",
                "types-docutils",
                "types-networkx",
                "types-pexpect",
                "types-psutil",
                "types-pycurl",
                "types-openpyxl",
                "types-python-dateutil",
                "types-pytz",
                "types-setuptools",
            ],
            expected_success=("mypy",),
            cost={"mypy": 140, "pyright": 170},
        ),
        Project(
            location="https://github.com/pallets/werkzeug",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/werkzeug", "tests"],
            deps=["types-setuptools", "pytest", "markupsafe"],
            expected_success=("mypy",),
            cost={"mypy": 21},
        ),
        Project(
            location="https://github.com/pallets/jinja",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["markupsafe"],
            expected_success=("mypy",),
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/mystor/git-revise",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["gitrevise"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/PyGithub/PyGithub",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["github", "tests"],
            deps=["types-requests", "pyjwt"],
            expected_success=("mypy",),
            cost={"mypy": 18},
        ),
        Project(
            location="https://github.com/we-like-parsers/pegen",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/pegen"],
            expected_success=("mypy",),
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/zulip/zulip",
            mypy_cmd="{mypy} zerver zilencer zproject tools analytics corporate scripts --platform=linux --config-file=",
            pyright_cmd="{pyright}",
            deps=[
                "types-PyYAML",
                "types-polib",
                "types-redis",
                "types-Markdown",
                "types-decorator",
                "types-pytz",
                "types-requests",
                "types-python-dateutil",
                "types-orjson",
                "cryptography",
                "django-stubs",
            ],
            # TODO: the plugin here is a little involved and might only work on linux
            # figure out what it would take to make it actually work
            # needs_mypy_plugins=True,
            expected_success=("mypy",),
            cost={"pyright": 60, "mypy": 102},
        ),
        Project(
            location="https://github.com/dropbox/stone",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["stone", "test"],
            deps=["types-six"],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/yelp/paasta",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["paasta_tools"],
            deps=[
                "types-cachetools",
                "types-croniter",
                "types-python-dateutil",
                "types-pytz",
                "types-PyYAML",
                "types-requests",
                "types-retry",
                "types-simplejson",
                "types-tzlocal",
                "types-ujson",
            ],
            cost={"mypy": 20},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/PrefectHQ/prefect",
            mypy_cmd="{mypy} src/prefect --exclude conftest.py",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=[
                "types-python-dateutil",
                "types-requests",
                "types-simplejson",
                "types-toml",
                "types-croniter",
                "types-PyYAML",
                "types-python-slugify",
                "types-pytz",
                "cryptography",
                "SQLAlchemy",
                "pydantic",
            ],
            needs_mypy_plugins=True,
            cost={"mypy": 36, "pyright": 60},
        ),
        Project(
            location="https://github.com/pallets/itsdangerous",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/itsdangerous"],
            deps=["pytest"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/jab/bidict",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["bidict"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/jaraco/zipp",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["zipp"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/aaugustin/websockets",
            mypy_cmd="{mypy} --strict {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["werkzeug"],
            expected_success=("mypy",),
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/pycqa/isort",
            mypy_cmd="{mypy} --ignore-missing-imports {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["isort"],
            deps=["types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 10},
        ),
        Project(
            location="https://github.com/aio-libs/aioredis",
            mypy_cmd="{mypy} {paths} --ignore-missing-imports",
            pyright_cmd="{pyright} {paths}",
            paths=["aioredis"],
            cost={"mypy": 9},
        ),
        Project(
            location="https://github.com/agronholm/anyio",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            expected_success=("mypy",),
            cost={"mypy": 9},
        ),
        Project(
            location="https://github.com/aio-libs/yarl",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["yarl", "tests"],
            deps=["multidict", "pytest"],
            expected_success=("mypy",),
            cost={"mypy": 14},
        ),
        Project(
            location="https://github.com/freqtrade/freqtrade",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["freqtrade", "scripts"],
            deps=[
                "numpy",
                "pandas-stubs",
                "pydantic",
                "sqlalchemy",
                "types-cachetools",
                "types-filelock",
                "types-python-dateutil",
                "types-requests",
                "types-tabulate",
            ],
            needs_mypy_plugins=True,
            expected_success=("mypy", "pyright"),
            cost={"mypy": 95},
        ),
        Project(
            location="https://github.com/google/jax",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["jax"],
            deps=["ml_dtypes", "numpy", "scipy-stubs", "types-requests"],
            expected_success=("mypy",),
            cost={"mypy": 178, "pyright": 90},
        ),
        Project(
            location="https://github.com/dulwich/dulwich",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["dulwich"],
            deps=["types-certifi", "types-paramiko", "types-requests"],
            expected_success=("mypy",),
            cost={"mypy": 15},
        ),
        Project(
            location="https://github.com/optuna/optuna",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=[
                "alembic",
                "numpy",
                "packaging",
                "sqlalchemy",
                "types-PyYAML",
                "types-redis",
                "types-setuptools",
                "types-tqdm",
                "typing-extensions",
            ],
            expected_success=("mypy",),
            cost={"mypy": 101, "pyright": 70},
        ),
        Project(
            location="https://github.com/trailofbits/manticore",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["types-protobuf", "types-PyYAML", "types-redis", "types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 50, "pyright": 75},
        ),
        Project(
            location="https://github.com/aiortc/aiortc",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["cryptography", "types-pyOpenSSL"],
            expected_success=("mypy",),
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/Textualize/rich",
            mypy_cmd="{mypy} -p rich --ignore-missing-imports --warn-unreachable",
            pyright_cmd="{pyright}",
            deps=["attrs"],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/dedupeio/dedupe",
            mypy_cmd="{mypy} --ignore-missing-imports {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["dedupe"],
            deps=["numpy"],
            needs_mypy_plugins=True,
            expected_success=("mypy",),
            cost={"mypy": 27},
        ),
        Project(
            location="https://github.com/schemathesis/schemathesis",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/schemathesis"],
            deps=["attrs", "types-requests", "types-PyYAML", "hypothesis"],
            expected_success=("mypy",),
            cost={"mypy": 24},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/graphql-python/graphql-core",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "tests"],
            deps=["pytest"],
            expected_success=("mypy",),
            cost={"mypy": 110},
        ),
        Project(
            location="https://github.com/Legrandin/pycryptodome",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["lib"],
            deps=["pycryptodome-test-vectors"],
            expected_success=("mypy",),
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/niklasf/python-chess",
            mypy_cmd="{mypy} --strict {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["chess"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/pytorch/ignite",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["packaging"],
            expected_success=("mypy",),
            cost={"pyright": 50, "mypy": 11},
        ),
        Project(
            location="https://github.com/pytorch/vision",
            mypy_cmd=None,  # "{mypy}",
            pyright_cmd="{pyright}",
            deps=["numpy", "pillow"],
            cost={"pyright": 50},
        ),
        Project(
            location="https://github.com/pypa/packaging",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            expected_success=("mypy",),
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/pydantic/pydantic",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pydantic"],
            deps=["annotated-types", "pydantic-core", "typing-extensions", "typing-inspection"],
            expected_success=("mypy",),
            cost={"mypy": 18},
        ),
        Project(
            location="https://github.com/encode/starlette",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["starlette", "tests"],
            deps=["anyio", "types-requests", "types-PyYAML"],
            expected_success=("mypy",),
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/aio-libs/janus",
            mypy_cmd="{mypy} {paths} --disallow-untyped-calls --disallow-incomplete-defs --strict",
            pyright_cmd="{pyright} {paths}",
            paths=["janus"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/alerta/alerta",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["alerta", "tests"],
            deps=["types-PyYAML", "types-setuptools", "types-requests", "types-pytz"],
            expected_success=("mypy",),
            cost={"mypy": 15},
        ),
        Project(
            location="https://github.com/nolar/kopf",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["kopf"],
            deps=["types-setuptools", "types-PyYAML"],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/davidhalter/parso",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["parso"],
            expected_success=("mypy",),
            cost={"pyright": 75, "mypy": 7},
        ),
        Project(
            location="https://github.com/konradhalas/dacite",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["dacite"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/ilevkivskyi/com2ann",
            mypy_cmd="{mypy} --python-version=3.9 src/com2ann.py src/test_com2ann.py",
            pyright_cmd="{pyright}",
            expected_success=("mypy",),
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/srittau/python-htmlgen",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["htmlgen", "test_htmlgen"],
            deps=["asserts"],
            expected_success=("mypy",),
            cost={"mypy": 8},
        ),
        Project(
            location="https://github.com/mitmproxy/mitmproxy",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["types-requests", "types-pyOpenSSL"],
            expected_success=("mypy",),
            cost={"mypy": 25},
        ),
        Project(
            location="https://github.com/jpadilla/pyjwt",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["jwt"],
            deps=["cryptography"],
            expected_success=("mypy",),
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/apache/spark",
            mypy_cmd="{mypy} --config python/mypy.ini {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["python/pyspark"],
            deps=["numpy", "pandas-stubs"],
            expected_success=("mypy",),
            cost={"mypy": 61, "pyright": 110},
        ),
        Project(
            location="https://github.com/laowantong/paroxython",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["paroxython"],
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/Akuli/porcupine",
            mypy_cmd="{mypy} --config-file= {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["porcupine"],
            deps=[
                "types-colorama",
                "types-psutil",
                "types-Pygments",
                "types-PyYAML",
                "types-requests",
                "types-Send2Trash",
                "types-tree-sitter-languages",
                "types-tree-sitter",
            ],
            expected_success=("mypy",),
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/dropbox/mypy-protobuf",
            mypy_cmd="{mypy} mypy_protobuf/",
            pyright_cmd="{pyright}",
            deps=["types-protobuf"],
            expected_success=("mypy",),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/spack/spack",
            mypy_cmd="{mypy} -p spack -p llnl",
            pyright_cmd="{pyright}",
            expected_success=("mypy",),
            cost={"mypy": 54, "pyright": 100},
        ),
        Project(
            location="https://github.com/johtso/httpx-caching",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["types-freezegun", "types-mock", "httpx", "anyio", "pytest"],
            expected_success=("mypy",),
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/python-poetry/poetry",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["types-requests", "pytest"],
            cost={"mypy": 30},
        ),
        Project(
            location="https://github.com/awslabs/sockeye",
            mypy_cmd="{mypy} --ignore-missing-imports --follow-imports=silent @typechecked-files --no-strict-optional",
            pyright_cmd=None,
            deps=["types-PyYAML"],
            expected_success=("mypy",),
            cost={"mypy": 14},
        ),
        Project(
            location="https://github.com/wntrblm/nox",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["nox"],
            deps=[
                "jinja2",
                "packaging",
                "importlib_metadata",
                "dependency-groups",
                "argcomplete",
                "attrs",
                "colorlog",
                "tomli",
                "importlib_resources",
                "uv",
            ],
            expected_success=("mypy",),
            cost={"mypy": 12},
        ),
        Project(
            location="https://github.com/pandera-dev/pandera",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pandera", "tests"],
            deps=[
                "numpy",
                "packaging",
                "pandas-stubs",
                "pydantic",
                "typeguard",
                "types-click",
                "types-PyYAML",
                "types-setuptools",
                "types-requests",
                "typing-inspect",
            ],
            expected_success=("mypy",),
            cost={"mypy": 53},
        ),
        Project(
            location="https://gitlab.com/cki-project/cki-lib",
            mypy_cmd="{mypy} --strict .",
            pyright_cmd="{pyright}",
            deps=["types-PyYAML", "cibuildwheel", "types-requests"],
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/python-jsonschema/check-jsonschema",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["types-jsonschema", "types-requests"],
            expected_success=("mypy",),
            cost={"mypy": 9},
        ),
        Project(
            location="https://github.com/pybind/pybind11",
            mypy_cmd="{mypy} --exclude '^(tests|docs)/' .",
            pyright_cmd="{pyright}",
            deps=["nox", "rich", "types-setuptools"],
            expected_success=("mypy",),
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/rpdelaney/downforeveryone",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["types-requests", "pytest"],
            expected_success=("mypy",),
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/DataDog/dd-trace-py",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=[
                "attrs",
                "types-six",
                "types-setuptools",
                "types-docutils",
                "types-PyYAML",
                "types-protobuf",
                "envier",
            ],
            needs_mypy_plugins=True,
            expected_success=("mypy",),
            cost={"pyright": 75, "mypy": 31},
        ),
        Project(
            location="https://github.com/systemd/mkosi",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["mkosi"],
            deps=["cryptography"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/sympy/sympy",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["sympy"],
            deps=["mpmath"],
            expected_success=("mypy",),
            cost={"mypy": 127, "pyright": 240},
        ),
        Project(
            location="https://github.com/nion-software/nionutils",
            mypy_cmd="{mypy} --strict -p nion.utils --config-file=",
            pyright_cmd="{pyright}",
            expected_success=("mypy",),
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/PyCQA/flake8-pyi",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["flake8_pyi"],
            deps=["types-pyflakes"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/internetarchive/openlibrary",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["openlibrary"],
            deps=[
                "types-PyYAML",
                "types-python-dateutil",
                "types-requests",
                "types-simplejson",
                "types-Deprecated",
            ],
            expected_success=("mypy",),
            cost={"mypy": 23},
        ),
        Project(
            location="https://github.com/JohannesBuchner/imagehash",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["imagehash"],
            deps=["PyWavelets", "numpy", "scipy-stubs", "types-Pillow"],
            expected_success=("mypy",),
            cost={"mypy": 43},
        ),
        Project(
            location="https://github.com/Kalmat/PyWinCtl",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/pywinctl"],
            deps=["types-setuptools", "types-pywin32", "types-python-xlib"],
            cost={"mypy": 9},
        ),
        Project(
            location="https://github.com/mesonbuild/meson",
            mypy_cmd="./run_mypy.py --mypy {mypy}",
            pyright_cmd=None,
            deps=["types-PyYAML", "coverage", "types-chevron", "types-PyYAML", "types-tqdm"],
            expected_success=("mypy",),
            cost={"mypy": 43},
        ),
        Project(
            location="https://github.com/aio-libs/aiohttp-devtools",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["aiohttp", "watchfiles", "types-pygments"],
            expected_success=("mypy",),
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/sco1/pylox",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["attrs", "pytest"],
            expected_success=("mypy",),
            cost={"mypy": 13},
            min_python_version=(3, 10),
        ),
        Project(
            location="https://github.com/ppb/ppb-vector",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["ppb_vector", "tests"],
            deps=["hypothesis"],
            expected_success=("mypy",),
            cost={"mypy": 14},
            min_python_version=(3, 10),
        ),
        Project(
            location="https://github.com/mkdocs/mkdocs",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["mkdocs"],
            deps=[
                "babel",
                "types-Markdown",
                "types-pytz",
                "types-PyYAML",
                "types-setuptools",
                "jinja2",
                "click",
                "watchdog",
                "pathspec",
                "platformdirs",
                "packaging",
            ],
            expected_success=("mypy",),
            cost={"mypy": 17},
        ),
        Project(
            location="https://github.com/astropenguin/xarray-dataclasses",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["xarray_dataclasses"],
            deps=["numpy", "xarray"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/scipy/scipy-stubs",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["numpy", "optype", "packaging", "scipy"],
            expected_success=("mypy", "pyright"),
            cost={"mypy": 111},
        ),
        Project(
            location="https://github.com/typeddjango/django-stubs",
            mypy_cmd="{mypy} django-stubs",
            pyright_cmd=None,
            install_cmd="{install} . ./ext",
            deps=["asgiref", "django-stubs-ext", "django", "redis", "tomli", "types-PyYAML"],
            needs_mypy_plugins=True,
            expected_success=("mypy",),
            cost={"mypy": 19},
        ),
        Project(
            location="https://github.com/pyppeteer/pyppeteer",
            mypy_cmd="{mypy} {paths} --config-file tox.ini",
            pyright_cmd="{pyright} {paths}",
            paths=["pyppeteer"],
            install_cmd="{install} .",
            cost={"mypy": 10},
        ),
        Project(
            location="https://github.com/pypa/pip",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            cost={"pyright": 45, "mypy": 24},
        ),
        Project(
            location="https://github.com/tornadoweb/tornado",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["tornado"],
            deps=["types-contextvars", "types-pycurl"],
            cost={"mypy": 17},
        ),
        Project(
            location="https://github.com/scipy/scipy",
            mypy_cmd="{mypy} scipy",
            pyright_cmd=None,
            deps=["numpy", "pytest", "hypothesis", "setuptools>=71.1", "types-psutil"],
            needs_mypy_plugins=True,
            cost={"mypy": 80},
        ),
        Project(
            location="https://github.com/pycqa/flake8",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "tests"],
            deps=["pytest"],
            cost={"mypy": 13},
        ),
        Project(
            location="https://github.com/home-assistant/core",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["homeassistant"],
            deps=[
                "attrs",
                "pydantic",
                "types-setuptools",
                "types-atomicwrites",
                "types-certifi",
                "types-croniter",
                "types-PyYAML",
                "types-requests",
                "types-python-slugify",
                "types-backports",
            ],
            needs_mypy_plugins=True,
            cost={"mypy": 3, "pyright": 240},
        ),
        Project(
            location="https://github.com/kornia/kornia",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["kornia"],
            cost={"mypy": 21},
        ),
        Project(
            location="https://github.com/ibis-project/ibis",
            mypy_cmd="{mypy} --ignore-missing-imports {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["ibis"],
            deps=[
                "SQLAlchemy",
                "numpy",
                "packaging",
                "pandas-stubs",
                "pyarrow",
                "types-python-dateutil",
                "types-pytz",
                "types-requests",
                "types-setuptools",
            ],
            cost={"mypy": 77, "pyright": 60},
        ),
        Project(
            location="https://github.com/streamlit/streamlit",
            mypy_cmd="{mypy} --config-file=lib/mypy.ini {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["lib", "scripts"],
            deps=[
                "attrs",
                "tornado",
                "packaging",
                "types-toml",
                "types-python-dateutil",
                "types-setuptools",
                "types-protobuf",
                "types-pytz",
                "types-requests",
                "types-cffi",
                "click",
                "pytest",
            ],
            cost={"mypy": 37, "pyright": 50},
        ),
        Project(
            location="https://github.com/dragonchain/dragonchain",
            mypy_cmd="{mypy} {paths} --error-summary",
            pyright_cmd="{pyright} {paths}",
            paths=["dragonchain"],
            deps=["types-redis", "types-requests"],
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/mikeshardmind/SinbadCogs",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["attrs", "types-pytz", "types-python-dateutil", "types-PyYAML"],
            cost={"mypy": 9},
        ),
        Project(
            location="https://github.com/rotki/rotki",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["rotkehlchen", "tools/data_faker"],
            deps=["eth-typing", "types-requests", "types-setuptools"],
            cost={"pyright": 60, "mypy": 11},
        ),
        Project(
            location="https://github.com/arviz-devs/arviz",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["numpy", "pytest", "scipy-stubs", "types-setuptools", "types-ujson", "xarray"],
            cost={"pyright": 45, "mypy": 71},
        ),
        Project(
            location="https://github.com/urllib3/urllib3",
            mypy_cmd="{mypy} {paths} --exclude setup.py",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=[
                "idna>=2.0.0",
                "cryptography>=1.3.4",
                "tornado>=6.1",
                "pytest",
                "trustme==0.9.0",
                "types-backports",
                "types-requests",
            ],
            cost={"mypy": 21},
        ),
        Project(
            location="https://github.com/common-workflow-language/schema_salad",
            mypy_cmd="MYPYPATH=$MYPYPATH:mypy-stubs {mypy} schema_salad",
            pyright_cmd=None,
            install_cmd="{install} $(grep -v mypy mypy-requirements.txt) -r requirements.txt",
            expected_success=("mypy",),
            cost={"mypy": 23},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/common-workflow-language/cwltool",
            mypy_cmd="MYPYPATH=$MYPYPATH:mypy-stubs {mypy} cwltool tests/*.py setup.py",
            pyright_cmd=None,
            install_cmd="{install} $(grep -v mypy mypy-requirements.txt) -r requirements.txt",
            expected_success=("mypy",),
            cost={"mypy": 71},
            supported_platforms=["linux", "darwin"],
        ),
        Project(
            location="https://github.com/AlexWaygood/typeshed-stats",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["attrs", "cattrs", "pytest", "aiohttp", "pathspec", "jinja2", "tomli"],
            cost={"mypy": 21},
        ),
        Project(
            location="https://github.com/FasterSpeeding/Tanjun",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["tanjun"],
            deps=["hikari", "alluka"],
            cost={"mypy": 29},
        ),
        Project(
            location="https://github.com/joerick/pyinstrument",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pyinstrument"],
            cost={"mypy": 8},
        ),
        Project(
            location="https://github.com/Gobot1234/steam.py",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["steam"],
            deps=["cryptography"],
            cost={"mypy": 23},
        ),
        Project(
            location="https://github.com/cpitclaudel/alectryon",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["alectryon.py"],
            deps=["types-docutils"],
            expected_success=("pyright",),
            cost={"mypy": 8},
        ),
        Project(
            location="https://github.com/yurijmikhalevich/rclip",
            mypy_cmd="{mypy} {paths} --explicit-package-bases",
            pyright_cmd="{pyright} {paths}",
            paths=["rclip"],
            deps=["numpy", "types-Pillow", "types-requests", "types-tqdm"],
            cost={"mypy": 16},
        ),
        Project(
            location="https://github.com/psycopg/psycopg",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["pytest", "pproxy"],
            cost={"mypy": 28},
        ),
        Project(
            location="https://gitlab.com/dkg/python-sop",
            mypy_cmd="{mypy} --strict {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["sop"],
            expected_success=("pyright",),
            cost={"mypy": 4},
        ),
        Project(
            location="https://github.com/Rapptz/discord.py",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["discord"],
            deps=["types-requests", "types-setuptools", "aiohttp"],
            expected_success=("pyright",),
            cost={"mypy": 77},
        ),
        Project(
            location="https://github.com/canonical/cloud-init",
            mypy_cmd="{mypy} cloudinit/ tests/ tools/",
            pyright_cmd="{pyright}",
            deps=[
                "jinja2",
                "pytest",
                "types-jsonschema",
                "types-oauthlib",
                "types-pyyaml",
                "types-requests",
                "types-setuptools",
            ],
            cost={"mypy": 47, "pyright": 50},
        ),
        Project(
            location="https://github.com/mongodb/mongo-python-driver",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["bson", "gridfs", "tools", "pymongo"],
            deps=["types-requests", "types-pyOpenSSL", "cryptography", "certifi"],
            cost={"mypy": 23},
        ),
        Project(
            location="https://github.com/artigraph/artigraph",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["pydantic", "numpy", "pytest"],
            needs_mypy_plugins=True,
            cost={"mypy": 27},
        ),
        Project(
            location="https://github.com/MaterializeInc/materialize",
            mypy_cmd="MYPYPATH=$MYPYPATH:misc/python {mypy} --explicit-package-bases misc/python",
            pyright_cmd="{pyright}",
            install_cmd="{install} -r ci/builder/requirements.txt",
            cost={"mypy": 62},
        ),
        Project(
            location="https://github.com/canonical/operator",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["ops"],
            deps=["types-PyYAML"],
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/caronc/apprise",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=[
                "types-six",
                "types-mock",
                "cryptography",
                "types-requests",
                "types-Markdown",
                "pytest",
                "certifi",
                "babel",
            ],
            cost={"mypy": 29},
        ),
        Project(
            location="https://github.com/Finistere/antidote",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["pytest"],
            cost={"mypy": 20},
        ),
        Project(
            location="https://github.com/cognitedata/Expression",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["pytest"],
            cost={"mypy": 15},
        ),
        Project(
            location="https://github.com/pyodide/pyodide",
            mypy_cmd="{mypy} {paths} --exclude 'setup.py|^src/tests|conftest.py'",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "pyodide-build"],
            deps=[
                "packaging",
                "types-docutils",
                "types-pyyaml",
                "types-setuptools",
                "numpy",
                "pydantic",
            ],
            needs_mypy_plugins=True,
            cost={"mypy": 19},
        ),
        Project(
            location="https://github.com/bokeh/bokeh",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "release"],
            deps=["types-boto", "tornado", "numpy", "jinja2", "selenium"],
            cost={"pyright": 60, "mypy": 39},
        ),
        Project(
            location="https://github.com/pandas-dev/pandas-stubs",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pandas-stubs", "tests"],
            deps=[
                "numpy",
                "types-pytz",
                "matplotlib",
                "xarray",
                "pyarrow",
                "jinja2",
                "pytest",
                "SQLAlchemy",
            ],
            expected_success=("pyright",),
            cost={"mypy": 161, "pyright": 75},
        ),
        Project(
            location="https://github.com/enthought/comtypes",
            mypy_cmd="{mypy} {paths} --platform win32",
            pyright_cmd="{pyright} {paths}",
            paths=["comtypes"],
            deps=["numpy"],
            cost={"mypy": 20},
        ),
        Project(
            location="https://github.com/mit-ll-responsible-ai/hydra-zen",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "tests/annotations"],
            deps=["pydantic", "beartype", "hydra-core"],
            cost={"mypy": 36},
        ),
        Project(
            location="https://github.com/Toufool/AutoSplit",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=[
                "certifi",
                "ImageHash",
                "numpy",
                "packaging",
                "PyWinCtl",
                "PySide6-Essentials",
                "scipy-stubs",
                "types-D3DShot",
                "types-keyboard",
                "types-Pillow",
                "types-psutil",
                "types-PyAutoGUI",
                "types-pyinstaller",
                "types-pywin32",
                "types-requests",
                "types-toml",
            ],
            cost={"mypy": 53},
        ),
        Project(
            location="https://github.com/Avasam/speedrun.com_global_scoreboard_webapp",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["backend"],
            deps=[
                "Flask",
                "PyJWT",
                "requests-cache",
                "types-Flask-SQLAlchemy",
                "types-httplib2",
                "types-requests",
            ],
            cost={"mypy": 22},
        ),
        Project(
            location="https://github.com/pwndbg/pwndbg",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pwndbg"],
            deps=["types-gdb"],
            cost={"mypy": 32, "pyright": 75},
        ),
        Project(
            location="https://github.com/keithasaurus/koda-validate",
            mypy_cmd="{mypy} {paths} --strict",
            pyright_cmd="{pyright} {paths}",
            paths=["koda_validate"],
            deps=["koda"],
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/python/cpython",
            mypy_cmd="{mypy} --config-file Tools/clinic/mypy.ini",
            pyright_cmd=None,
            name_override="CPython (Argument Clinic)",
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/python/cpython",
            mypy_cmd="{mypy} --config-file Tools/cases_generator/mypy.ini",
            pyright_cmd=None,
            name_override="CPython (cases_generator)",
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/python/cpython",
            mypy_cmd="{mypy} --config-file Tools/peg_generator/mypy.ini",
            pyright_cmd=None,
            name_override="CPython (peg_generator)",
            deps=["types-setuptools", "types-psutil"],
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/python-trio/trio",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src/trio"],
            deps=[
                "types-pyOpenSSL",
                "types-cffi",
                "attrs",
                "outcome",
                "exceptiongroup",
                "pytest",
                "sniffio",
            ],
            cost={"mypy": 29},
        ),
        Project(
            location="https://github.com/pypa/setuptools",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["setuptools", "pkg_resources"],
            deps=["pytest", "filelock", "ini2toml", "packaging", "tomli", "tomli-w"],
            expected_success=("pyright",),
            cost={"mypy": 20},
        ),
        Project(
            location="https://github.com/detachhead/pytest-robotframework",
            mypy_cmd="{mypy} -p pytest_robotframework",
            pyright_cmd="{pyright}",
            cost={"mypy": 5},
        ),
        Project(
            location="https://github.com/mhammond/pywin32",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["types-pywin32", "types-regex", "types-setuptools"],
            cost={"mypy": 20},
        ),
        Project(
            location="https://github.com/beartype/beartype",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["beartype"],
            cost={"mypy": 11},
        ),
        Project(
            location="https://github.com/colour-science/colour",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["colour"],
            deps=["matplotlib", "numpy", "pandas-stubs", "pytest", "scipy-stubs"],
            cost={"mypy": 1500, "pyright": 180},
        ),
        Project(
            location="https://github.com/vega/altair",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["altair", "tests"],
            deps=[
                "jinja2",
                "narwhals",
                "numpy",
                "packaging",
                "pandas-stubs",
                "pyarrow-stubs",
                "pytest",
                "scipy-stubs",
                "types-jsonschema",
            ],
            cost={"mypy": 94},
        ),
        Project(
            location="https://github.com/hydpy-dev/hydpy",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["hydpy"],
            deps=["numpy", "pandas-stubs", "scipy-stubs", "types-docutils", "types-networkx"],
            cost={"mypy": 99},
        ),
        Project(
            location="https://github.com/static-frame/static-frame",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["static_frame"],
            deps=["numpy", "arraykit==0.10.0"],
            cost={"mypy": 101},
        ),
        Project(
            location="https://github.com/mikeshardmind/async-utils",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            expected_success=("pyright",),
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/pypa/cibuildwheel",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["cibuildwheel"],
            deps=[
                "bracex",
                "certifi",
                "dependency-groups",
                "filelock",
                "packaging",
                "platformdirs",
                "uv",
            ],
            cost={"mypy": 10},
        ),
        Project(
            location="https://github.com/pypa/build",
            mypy_cmd="{mypy}",
            pyright_cmd="{pyright}",
            deps=["importlib_metadata", "packaging", "pyproject_hooks", "tomli", "uv"],
            cost={"mypy": 7},
        ),
        Project(
            location="https://github.com/pypa/pyproject-metadata",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["pyproject_metadata"],
            deps=["packaging"],
            expected_success=("pyright",),
            cost={"mypy": 6},
        ),
        Project(
            location="https://github.com/strawberry-graphql/strawberry",
            mypy_cmd="{mypy} {paths} --config-file=",
            pyright_cmd="{pyright} {paths}",
            paths=["strawberry"],
            deps=["graphql-core", "python-dateutil", "packaging"],
            cost={"mypy": 17},
        ),
        Project(
            location="https://github.com/archlinux/archinstall",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["."],
            deps=["cryptography", "pydantic", "pytest"],
            cost={"mypy": 24},
        ),
        Project(
            location="https://github.com/zopefoundation/zope.interface",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            deps=["zope.testing"],
        ),
        Project(
            location="https://github.com/scikit-build/scikit-build-core",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "tests", "noxfile.py"],
            deps=[
                "build",
                "cattrs",
                "cmake",
                "exceptiongroup",
                "hatch-fancy-pypi-readme",
                "importlib-resources",
                "markdown-it-py",
                "ninja",
                "nox",
                "orjson",
                "packaging",
                "pytest",
                "pytest-subprocess",
                "rich",
                "setuptools-scm",
                "tomli",
                "types-setuptools",
            ],
            cost={"mypy": 34},
        ),
        Project(
            location="https://github.com/hynek/svcs",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src", "tests/typing"],
            deps=["attrs", "flask", "aiohttp", "fastapi", "starlette"],
            expected_success=("mypy", "pyright"),
        ),
        Project(
            location="https://github.com/glyph/DateType",
            mypy_cmd="{mypy} {paths}",
            pyright_cmd="{pyright} {paths}",
            paths=["src"],
            expected_success=("mypy",),
        ),
    ]
    assert len(projects) == len({p.name for p in projects})
    for p in projects:
        assert p.supported_platforms is None or all(
            p in ("linux", "darwin") for p in p.supported_platforms
        )
    return projects
